services:
  nginx:
    image: nginx:1.25.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./files:/var/www/files
    ports:
      - 80:80

  imageproxy:
    image: willnorris/imageproxy
    restart: always
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=username
      - AWS_SECRET_KEY=password
    command: -addr 0.0.0.0:8080 -cache 's3://fake-region/test?endpoint=minio:9000&disableSSL=1&s3ForcePathStyle=1'

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
    restart: always
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
